lib/libra_web/router.ex
defmodule LibraWeb.Router do
  use LibraWeb, :router
  use Pow.Phoenix.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :protected do
    plug Pow.Plug.RequireAuthenticated,
      error_handler: Pow.Phoenix.PlugErrorHandler
  end

  scope "/" do
    pipe_through :browser

    pow_routes()
  end

  scope "/", LibraWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/home", PageController, :index

    get "/buy", BuyController, :buy

    pipe_through :protected
    get "/sell", SellController, :sell
    post "/create", SellController, :create
  end
end

lib/libra/application.ex
defmodule Libra.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    # List all child processes to be supervised
    children = [
      # Start the Ecto repository
      Libra.Repo,
      # Start the endpoint when the application starts
      LibraWeb.Endpoint
      # Starts a worker by calling: Libra.Worker.start_link(arg)
      # {Libra.Worker, arg},
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Libra.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    LibraWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/libra/book.ex
defmodule Libra.Book do
  use Ecto.Schema
  alias Libra.Repo
  import Ecto.Changeset

  schema "books" do
    field :title, :string
    field :authors, {:array, :string}
    field :isbn_13, :string
    field :image, :string
    field :page_count, :integer

    timestamps()
  end

  @doc false
  def changeset(book, params \\ %{}) do
    book
    |> cast(params, [:title, :authors, :image, :isbn_13, :page_count])
    |> unique_constraint(:isbn_13_constraint, name: :pk_isbn_13)
    |> validate_required([:title, :authors, :image, :isbn_13, :page_count])
  end

  def upsert(changeset) do
    Repo.insert!(
      changeset,
      on_conflict: :replace_all_except_primary_key,
      conflict_target: :isbn_13
    )
  end

end

lib/libra/listing.ex
defmodule Libra.Listing do
  use Ecto.Schema
  alias Libra.{Repo, Book, Users.User}

  import Ecto.Changeset

  schema "listings" do
    field :description, :string
    field :price, :decimal
    belongs_to :user, User
    belongs_to :book, Book

    timestamps()
  end

  @doc false
  def changeset(listing, params \\ %{}) do
    listing
    |> cast(params, [:description, :price, :user_id, :book_id])
    |> validate_required([:description, :price, :user_id, :book_id])
  end

end

lib/libra/open_library.ex
defmodule Libra.OpenLibrary do
  require Logger
  require HTTPoison

  def getByIsbn(isbn) do
    url = "https://openlibrary.org/api/books?bibkeys=ISBN:#{isbn}&format=json&jscmd=data"

    case HTTPoison.get(url) do
      {:ok, %HTTPoison.Response{status_code: 200, body: body}} ->
        req = Poison.decode!(body)

        book_data = req["ISBN:#{isbn}"]

        %{
          :isbn_13 => isbn,
          :title => book_data["title"],
          :image => get_in(book_data, ["cover", "medium"]),
          :authors => book_data["authors"]
                      |> Enum.map(fn x -> get_in(x, ["name"])end ),
          :page_count => book_data["number_of_pages"]
        }

      {:ok, %HTTPoison.Response{status_code: 404}} ->
        Logger.info("Not found :(")

      {:error, %HTTPoison.Error{reason: reason}} ->
        Logger.error(reason)

    end
  end
end

lib/libra/repo.ex
defmodule Libra.Repo do
  use Ecto.Repo,
    otp_app: :libra,
    adapter: Ecto.Adapters.Postgres
end

lib/libra/users/user.ex
defmodule Libra.Users.User do
  use Ecto.Schema
  use Pow.Ecto.Schema

  schema "users" do
    pow_user_fields()

    timestamps()
  end
end

lib/libra_web/controllers/buy_controller.ex
defmodule LibraWeb.BuyController do
  use LibraWeb, :controller
  import Ecto.Query
  alias Libra.{Repo, Listing, Book}
  require Logger

  def index(conn, _params) do
    render(conn, "index.html")
  end

  def buy(conn, %{"query" => query}) do
    listing_query = from l in Listing, join: b in Book, on: l.book_id == b.id, select: map(b, [:title, :image, :authors])

    books = Repo.all(listing_query)


    render(conn, "results.html", books: books)
  end
end

lib/libra_web/controllers/page_controller.ex
defmodule LibraWeb.PageController do
  require Logger
  require HTTPoison

  alias Libra.Book
  use LibraWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

lib/libra_web/controllers/sell_controller.ex
defmodule LibraWeb.SellController do
  use LibraWeb, :controller
  alias Libra.{Listing, Repo, Book, OpenLibrary}
  require Logger

  def sell(conn, %{"query" => query}) do
    book_rec = Repo.get_by(Book, isbn_13: query)

    if !book_rec do
      ol_record = OpenLibrary.getByIsbn(query)

      new_book =
        Book.changeset(%Book{}, ol_record)
        |> Book.upsert()
        |> Map.from_struct()

      render(conn, "new.html",
        book: new_book,
        book_id: new_book.id,
        listing_changeset: Listing.changeset(%Listing{})
      )
    end

    render(conn, "new.html",
      book: Map.from_struct(book_rec),
      book_id: book_rec.id,
      listing_changeset: Listing.changeset(%Listing{})
    )
  end

  def create(conn, %{"listing" => listing}) do
    current_user = Pow.Plug.current_user(conn)

    Listing.changeset(%Listing{}, Map.put(listing, "user_id", current_user.id))
    |> Repo.insert!()

    render(conn, "results.html")
  end
end

lib/libra_web/views/buy_view.ex
defmodule LibraWeb.BuyView do
  use LibraWeb, :view
end

lib/libra_web/views/error_view.ex
defmodule LibraWeb.ErrorView do
  use LibraWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/libra_web/views/layout_view.ex
defmodule LibraWeb.LayoutView do
  use LibraWeb, :view
end

lib/libra_web/views/page_view.ex
defmodule LibraWeb.PageView do
  use LibraWeb, :view
end

lib/libra_web/views/pow/registration_view.ex
defmodule LibraWeb.Pow.RegistrationView do
  use LibraWeb, :view
end

lib/libra_web/views/pow/session_view.ex
defmodule LibraWeb.Pow.SessionView do
  use LibraWeb, :view
end

lib/libra_web/views/sell_view.ex
defmodule LibraWeb.SellView do
  use LibraWeb, :view
end

lib/libra_web/views/shared_view.ex
defmodule LibraWeb.SharedView do
  use LibraWeb, :view
end

lib/libra_web/templates/buy/book.html.eex
<div class="Book-card">
    <span>
        <div class="Image-box">
            <img src=<%= @book[:image] %> alt="Book Cover" />
            <a href="#">Buy now!</a>
            <button class="View-btn">View</button>
        </div>
    </span>
    <div class="Text-box">
        <h4><%= @book[:title] %></h2>
        <p><%= @book[:authors] %></p>
        <h4><%= @book[:price] %></h4>
    </div>
</div>

lib/libra_web/templates/buy/results.html.eex
<div class="root">
    <%= render(LibraWeb.SharedView, "navbar.html") %>
    <div class="results-books">
        <%= if assigns[:books] do %>
            <%= for book <- @books do %>
                <%= render("book.html", book: book) %>
            <% end %>
        <% else %>
            <div>
                <p>No Results!</p>
            </div>
        <% end %>
    </div>
</div>

lib/libra_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Libra Dev</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script src="<%= Routes.static_path(@conn, "/js/app.js") %>"/></script>
  </head>
  <body>
      <%= render @view_module, @view_template, assigns %>
  </body>
</html>

lib/libra_web/templates/page/book.html.eex
<div class="Book-card">
    <span>
        <div class="Image-box">
            <img src=<%= @book[:image] %> alt="Book Cover" />
            <a href="/create?book=<%= @book[:id] %>">Buy now!</a>
            <button class="View-btn">View</button>
        </div>
    </span>
    <div class="Text-box">
        <h2><%= @book[:title] %></h2>
        <p><%= @book[:description] %></p>
        <h4><%= @book[:price] %></h4>
    </div>
</div>

lib/libra_web/templates/page/index.html.eex
<div class="root">
    <div class="home-fullscreen-background">
        <div class="home-fullscreen-search">
            <%= render(LibraWeb.SharedView, "search.html") %>
        </div>
    </div>
    <div class="home-options">
        <div>
            <h2>
            <a href="?mode=buy">Buy</a>
            </h2>
        </div>
        <div>
            <h2>
            <a href="?mode=sell">Sell</a>
            </h2>
        </div>
    </div>
</div>

lib/libra_web/templates/page/navbar.html.eex
<div class="navbar">
    <%= render("search.html") %>
    <a class="navbar-brand" href="/"></a>
    <div class="navbar-info">
    <div class="navbar-item-list">
        <a class="nav-item" href="/">
        Home
        </a>
        <a class="nav-item" href="#">
        About
        </a>
    </div>
    </div>
</div>

lib/libra_web/templates/page/results.html.eex
<div class="Root">
    <%= render("navbar.html") %>
    <div class="results-books">
        <%= if assigns[:books] do %>
            <%= for book <- @books do %>
                <%= render("book.html", book: book) %>
            <% end %>
        <% else %>
            <div>
                <p>No Results!</p>
            </div>
        <% end %>
    </div>
</div>

lib/libra_web/templates/pow/session/new.html.eex
<div class="w-full max-w-xs">
    <%= form_for @changeset, @action, [as: :user, class: "bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4"], fn f -> %>
        <%= if @changeset.action do %>
            <div class="alert alert-danger">
                <p>Oops, something went wrong! Please check the errors below.</p>
            </div>
        <% end %>
        <div class="mb-4">

            <%= label f, Pow.Ecto.Schema.user_id_field(@changeset), class: "block text-gray-700 text-sm font-bold mb-2" %>
            <%= text_input f, Pow.Ecto.Schema.user_id_field(@changeset), class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
            <%= error_tag f, Pow.Ecto.Schema.user_id_field(@changeset) %>
        </div>

        <div class="mb-6">
            <%= label f, :password, class: "block text-gray-700 text-sm font-bold mb-2" %>
            <p class="text-red-500 text-xs italic">Please choose a password.</p>
            <%= password_input f, :password, [placeholder: "******************",class: "shadow appearance-none border border-red-500 rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline"]%>
            <%= error_tag f, :password %>
        </div>
        <div class="flex items-center justify-between">
            <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
                Sign in
            </button>
            <a class="inline-block align-baseline font-bold text-sm text-blue-500 hover:text-blue-800" href="#">
                Forgot Password?
    </a>
</div>

        <div>
        </div>
    <% end %>
</div>

<span><%= link "Register", to: Routes.pow_registration_path(@conn, :new) %></span>

lib/libra_web/templates/sell/book.html.eex
<div class="Book-card">
    <span>
        <div class="Image-box">
            <img src=<%= @book[:image] %> alt="Book Cover" />
            <button class="View-btn">View</button>
        </div>
    </span>
    <div class="Text-box">
        <h4><%= @book[:title] %></h4>
        <%= for author <- @book[:authors] do %>
            <p><%= author %></p>
        <% end %>
    </div>
</div>

lib/libra_web/templates/sell/new.html.eex
<%= render("book.html", book: @book) %>
<%= form_for @listing_changeset, Routes.sell_path(@conn, :create), fn f -> %>

    <label>
        Description: <%= text_input f, :description%>
    </label>

    <label>
        Price: <%= text_input f, :price %>
    </label>

    <%= hidden_input :listing, :book_id, value: @book_id %>

    <%= submit "Submit" %>
<% end %>

lib/libra_web/templates/sell/results.html.eex
<div class="root">
    <%= render(LibraWeb.SharedView, "navbar.html") %>
    <div class="results-books">
        <%= if assigns[:books] do %>
            <%= for book <- @books do %>
                <%= render("book.html", book: book) %>
            <% end %>
        <% else %>
            <div>
                <p>No Results!</p>
            </div>
        <% end %>
    </div>
</div>

lib/libra_web/templates/shared/navbar.html.eex
<div class="navbar">
    <%= render(LibraWeb.SharedView, "search.html") %>
    <a class="navbar-brand" href="/"></a>
    <div class="navbar-info">
    <div class="navbar-item-list">
        <a class="nav-item" href="/">
        home
        </a>
        <a class="nav-item" href="#">
        About
        </a>
    </div>
    </div>
</div>

lib/libra_web/templates/shared/search.html.eex
<div class="search-container" data-controller="search">
    <h1>Libra</h1>
    <input
      data-action="search#input"
      class="search-input"
      type="text"
      id="search-input"
    />
</div>